/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.hangouts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HangoutsGroup service. Represents a row in the &quot;rivetlogic_hangouts_HangoutsGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.hangouts.model.impl.HangoutsGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.hangouts.model.impl.HangoutsGroupImpl}.
 * </p>
 *
 * @author Rivet Logic
 * @see HangoutsGroup
 * @see com.rivetlogic.hangouts.model.impl.HangoutsGroupImpl
 * @see com.rivetlogic.hangouts.model.impl.HangoutsGroupModelImpl
 * @generated
 */
public interface HangoutsGroupModel extends BaseModel<HangoutsGroup> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hangouts group model instance should use the {@link HangoutsGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this hangouts group.
	 *
	 * @return the primary key of this hangouts group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hangouts group.
	 *
	 * @param primaryKey the primary key of this hangouts group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hangouts group ID of this hangouts group.
	 *
	 * @return the hangouts group ID of this hangouts group
	 */
	public long getHangoutsGroupId();

	/**
	 * Sets the hangouts group ID of this hangouts group.
	 *
	 * @param hangoutsGroupId the hangouts group ID of this hangouts group
	 */
	public void setHangoutsGroupId(long hangoutsGroupId);

	/**
	 * Returns the user ID of this hangouts group.
	 *
	 * @return the user ID of this hangouts group
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this hangouts group.
	 *
	 * @param userId the user ID of this hangouts group
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this hangouts group.
	 *
	 * @return the user uuid of this hangouts group
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this hangouts group.
	 *
	 * @param userUuid the user uuid of this hangouts group
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this hangouts group.
	 *
	 * @return the user name of this hangouts group
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this hangouts group.
	 *
	 * @param userName the user name of this hangouts group
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this hangouts group.
	 *
	 * @return the create date of this hangouts group
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this hangouts group.
	 *
	 * @param createDate the create date of this hangouts group
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this hangouts group.
	 *
	 * @return the modified date of this hangouts group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this hangouts group.
	 *
	 * @param modifiedDate the modified date of this hangouts group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group name of this hangouts group.
	 *
	 * @return the group name of this hangouts group
	 */
	@AutoEscape
	public String getGroupName();

	/**
	 * Sets the group name of this hangouts group.
	 *
	 * @param groupName the group name of this hangouts group
	 */
	public void setGroupName(String groupName);

	/**
	 * Returns the hangouts contacts of this hangouts group.
	 *
	 * @return the hangouts contacts of this hangouts group
	 */
	@AutoEscape
	public String getHangoutsContacts();

	/**
	 * Sets the hangouts contacts of this hangouts group.
	 *
	 * @param hangoutsContacts the hangouts contacts of this hangouts group
	 */
	public void setHangoutsContacts(String hangoutsContacts);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HangoutsGroup hangoutsGroup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HangoutsGroup> toCacheModel();

	@Override
	public HangoutsGroup toEscapedModel();

	@Override
	public HangoutsGroup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}